///////////////////////////////////////////////////////////
//  Compte_remunere.cs
//  Implementation of the Class Compte_remunere
//  Generated by Enterprise Architect
//  Created on:      12-juil.-2021 11:08:13
//  Original author: Stagiaire
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using System;
using System.Text;
using LibraryAppCompteBancaire;

namespace LibraryAppCompteBancaire{
	public class Compte_Remu : CompteClient 
		{
		public static double taux_Interet = 0.02;
		private DateTime date_Ouverture;
		private List<double> tabSoldesCompte = new List<double>();

		public Compte_Remu(long _numero, string _nom, double _solde, double _decouvertAutorise, int _jour, int _mois, int _annee) : base(_numero, _nom, _solde, _decouvertAutorise)
		{
			this.date_Ouverture = new DateTime(_annee, _mois, _jour);

			for (int i = 0; i <24; i++)
            {
				tabSoldesCompte.Add(_solde);
            }
		}
        public override string ToString()
        {
			return base.ToString() + "\n pour taux d'intérêt :" + taux_Interet + " et pour date d'ouverture "+ this.date_Ouverture.ToString("dd-MM-yyyy");
        }

		/// 
		/// <param name="_date"></param>
		public double Calculer_Interet(DateTime _date)
		{
			int temp;
			if (_date.Day > 15)
            {
				temp = _date.Month * 2 -1;
            }
            else
            {
				temp = _date.Month * 2 -2 ;
            }
			double sommeinterets = 0;
			for (int i = 0; i < temp; i++)
            {
				sommeinterets += this.tabSoldesCompte[i]*taux_Interet/(double)24;
            }
			return sommeinterets;
		}

        /// 
        /// <param name="_date"></param>
        /// <param name="montant"></param>
        //public override void Crediter(DateTime _date, float montant){

    //}

    //public Date date_ouverture()
    //{

    //    return null;
    //}

    /// 
    /// <param name="_date"></param>
    /// <param name="montant"></param>
    //public override bool Debiter(DateTime _date, float montant){

    //	return false;
    //}
    ///// 
    ///// <param name="_date"></param>
    ///// <param name="montant"></param>
    ///// <param name="autreCompte"></param>
    //public override bool Transferer(DateTime _date, float montant, Compte autreCompte)
    //{
    //	return false;
    //}

}//end Compte_remunere

}//end namespace BiblioBanque
